### ISSUE TITLE
Camera Colors

### ISSUE THREAD

**Issue by RobertSuto** [danielenapo/progetto_oop#2]
Hello, I tried to clone your repo and run it and I seem to run into a problem when pressing scan. Colors seems off (for example red color turns into blue). I'm gonna attach a picture so you can get an understanding. 
![image](https://user-images.githubusercontent.com/72727072/164895708-3e62c4d9-7a11-402f-b38e-05fba9ba0c9d.png)
Maybe you could instruct me how to fix this problem. Thanks in advance!

**Comment by danielenapo** [comment]
The app is very sensible to light conditions, as written in the instructions. I see that the image of your camera seems to be kinda blue, so maybe try to use another phone if you can, or else try to use a red light to contrast the blue effect maybe? 
Basically the app does a mean value of the RGB value of all the pixels inside each square, so that's why it recognizes it as blue instead of red (for example) even if the image is slightly more blue due to light conditions or problems in the camera. I don't know if it's a software problem, but it works kinda well on multiple phones I've tried it on.
